name: tsai_architectures
description: Try different architectures and datasets
method: grid
metric:
  goal: maximize
  name: accuracy
parameters:
  arch:
    distribution: categorical
    values:
        - ResNet
        - LSTM_FCN
        - InceptionTime
        - TST
  dsid:
      distribution: categorical
      values:
          - NATOPS
          - GunPoint
          - OliveOil
    