name: tsai_architectures
description: Try different architectures
method: grid
metric:
  goal: maximize
  name: accuracy
parameters:
  arch:
    distribution: categorical
    values:
        - OmniScaleCNN
        - ResNet
        - LSTM_FCN
        - XceptionTime
        - ResCNN
        - InceptionTime
        - xresnet1d34